### ISSUE TITLE
Dependency issue, possibly because ansible-galaxy is downloading v1.1.0?

### ISSUE THREAD

**Issue by thom-nic** [Stouts/Stouts.wale#14]
I installed this role via a line in a requirements.yml:

``` yml
- src: Stouts.wale
```

which appears to have installed v1.1.0:

```
ansible-galaxy install -r requirements.yml
....
- downloading role 'wale', owned by Stouts
- downloading role from https://github.com/Stouts/Stouts.wale/archive/1.1.0.tar.gz
- extracting Stouts.wale to .galaxy/Stouts.wale
- Stouts.wale was installed successfully
```

Now when I run the role on Ubuntu Trusty I get the following error:

```
TASK [Stouts.wale : Check backup-list] *****************************************
fatal: [vsdemo1]: FAILED! => {"changed": false, "cmd": ["/etc/wale/wale.sh", "backup-list"], "delta": "0:00:00.065290", "end": "2016-04-21 09:09:44.950490", "failed": true, "rc": 1, "start": "2016-04-21 09:09:44.885200", "stderr": "Traceback (most recent call last):\n  File \"/usr/local/bin/wal-e\", line 5, in <module>\n    from pkg_resources import load_entry_point\n  File \"/usr/lib/python2.7/dist-packages/pkg_resources.py\", line 2749, in <module>\n    working_set = WorkingSet._build_master()\n  File \"/usr/lib/python2.7/dist-packages/pkg_resources.py\", line 446, in _build_master\n    return cls._build_from_requirements(__requires__)\n  File \"/usr/lib/python2.7/dist-packages/pkg_resources.py\", line 459, in _build_from_requirements\n    dists = ws.resolve(reqs, Environment())\n  File \"/usr/lib/python2.7/dist-packages/pkg_resources.py\", line 628, in resolve\n    raise DistributionNotFound(req)\npkg_resources.DistributionNotFound: requests>=2.8.1,!=2.9.0", "stdout": "", "stdout_lines": [], "warnings": []}
```

formatted error:

```
Traceback (most recent call last):
  File "/usr/local/bin/wal-e", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 446, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 459, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: requests>=2.8.1,!=2.9.0"
```

So the error I believe may be the same as #11 however it appears this role is @ v1.1.3.  Does the Ansible galaxy index need to be updated? https://galaxy.ansible.com/Stouts/wale/

**Comment by thom-nic** [comment]
I just changed the role dependency to point to this github repo and re-installed v1.1.3 and re-ran the role.  Still appears to fail with the same error.  I _do_ see dependencies installed but not `request`:

```
TASK [Stouts.wale : Install requirements - pt. 1] ******************************
ok: [vsdemo1] => (item=[u'cron', u'libffi-dev', u'lzop', u'pv', u'python-dev', u'python-lxml', u'python-pip'])

TASK [Stouts.wale : Install requirements - pt. 2] ******************************
ok: [vsdemo1] => (item=six)
ok: [vsdemo1] => (item=wal-e)

TASK [Stouts.wale : Install requirements - pt. 2] ******************************
skipping: [vsdemo1] => (item=six) 
skipping: [vsdemo1] => (item=wal-e) 

....

TASK [Stouts.wale : Check backup-list] *****************************************
fatal: [vsdemo1]: FAILED! => {"changed": false, "cmd": ["/etc/wale/wale.sh", "backup-list"], "delta": "0:00:00.062012", "end": "2016-04-21 09:22:25.714262", "failed": true, "rc": 1, "start": "2016-04-21 09:22:25.652250", "stderr": "Traceback (most recent call last):\n  File \"/usr/local/bin/wal-e\", line 5, in <module>\n    from pkg_resources import load_entry_point\n  File \"/usr/lib/python2.7/dist-packages/pkg_resources.py\", line 2749, in <module>\n    working_set = WorkingSet._build_master()\n  File \"/usr/lib/python2.7/dist-packages/pkg_resources.py\", line 446, in _build_master\n    return cls._build_from_requirements(__requires__)\n  File \"/usr/lib/python2.7/dist-packages/pkg_resources.py\", line 459, in _build_from_requirements\n    dists = ws.resolve(reqs, Environment())\n  File \"/usr/lib/python2.7/dist-packages/pkg_resources.py\", line 628, in resolve\n    raise DistributionNotFound(req)\npkg_resources.DistributionNotFound: requests>=2.8.1,!=2.9.0", "stdout": "", "stdout_lines": [], "warnings": []}
```

**Comment by thom-nic** [comment]
Also tried setting `wale_latest: true`, saw the `six` dependency change but still same error.
